### PR TITLE
include bugfix for https://github.com/ga4gh/vrs-python/issues/63

### PR DESCRIPTION
**Pull request by bmrobin**

### CODE REVIEW

**Comment by andreasprlic** [comment]
Can we also add the changes to conftest.py? This is to be able to distinguish the local dataproxy and a rest proxy in unit test space...

**Comment by andreasprlic** [comment]
(also - can you sign your commit?)

**Comment by bmrobin** [comment]
yes sure.

> (also - can you sign your commit?)

i'm not sure what you mean... i'm frankly getting a little lost in all the forking (i tried to make these changes directly on your original branch, but got permission denied since it's "your repo").

is this not fine?
image

**Review by andreasprlic — APPROVED** [review]
thanks, LGTM

**Pull request merged**
